FROM ubuntu:latest

ENV PUBLIC_IP 127.0.0.1
ENV PORT 3478
ENV USERS admin=admin123
ENV SOCKET_TYPE tcp,udp
ENV REALM kerry

WORKDIR /root/turn-server

ADD turn-server-socket-amd64 turn-server
RUN chmod +x turn-server

CMD ./turn-server -public-ip $PUBLIC_IP -port $PORT -users=$USERS -realm=$REALM -socket-type=$SOCKET_TYPE